# CI/CD конфигурация проекта
# Основано на шаблоне
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# TODO - добиться подстановки переменных среды в джобах, сейчас по какой-то причине они не подставляются
# TODO - копия скриптов деплоя сохранена в ./deploy_scripts. Было бы неплохо перед запуском их обновлять
# TODO было бы круто вынести создание всех переменных среды используемых в скриптах в отдельный файл
variables:
  # Максимальное количество параллельно собираемых проектов при сборке решения; зависит от количества ядер ПК, выбранного для сборки
  # являются переменными среды и явно в вызовы не передаются, однако должны быть проинициализирвоанными
  MSBUILD_CONCURRENCY: "4"
  MSBuildSDKsPath: "C:\\Program Files\\dotnet\\sdk\\6.0.408\\Sdks"

  TMP_BUILD_FOLDER: "C:\\GitLabUtils\\build"                #бинарники собираемые для прогона тестов
  TMP_RELEASE_FOLDER: "C:\\GitLabUtils\\release"            #бинарники собираемые для деплоя
  DEPLOY_SCRIPT_PATH: "C:\\GitLabUtils\\deployDiploma.bat"  #скрипт вызываемый на продовой машине - выполняет подмену папок, подстановку строки подключения в конфиг и рестарт сервера
  
stages: 
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - branches
  before_script:
    - CHCP 65001 #смена кодировки консоли для корректного отображения текста ошибок
  script:
    - dotnet restore
    - dotnet build --configuration Release -o "C:\\GitLabUtils\\build"      #TMP_BUILD_FOLDER
    - dotnet publish --configuration Release -o "C:\\GitLabUtils\\release"  #TMP_RELEASE_FOLDER
  artifacts:
    expire_in: 2 days 
    paths:
      - '.\\Build' 


test_job: 
  stage: test   
  only: 
    - branches
  before_script:
    - CHCP 65001 #смена кодировки консоли для корректного отображения текста ошибок
  script:
    - echo "Running tests..."
    - dotnet test
  dependencies: 
    - build_job

deploy_job:
  stage: deploy
  only:
    - production
  before_script:
    - CHCP 65001 #смена кодировки консоли для корректного отображения текста ошибок
  script:
    - "& C:\\GitLabUtils\\deployDiploma.bat" #DEPLOY_SCRIPT_PATH
  environment: production